Prática 1 : **Exemplo** com Aprendizagem Supervisionada - CLASSIFICAÇÃO

**Link para a base de dados Diabetes:**  [Acesse aqui](https://www.kaggle.com/datasets/ehababoelnaga/diabetes-dataset)

# INICIAL

In [ ]:
# Imports

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Guardando os dados do CSV carregado em um Dataframe Pandas

base = pd.read_csv('Training.csv', sep=',')

In [ ]:
# Linhas x Colunas

base.shape

(2460, 9)

In [ ]:
# Mostrar a base de dados em si

base.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# Tipos de dados

base.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

#**Tratamento dos Dados:**

In [ ]:
# Mudar o nome das colunas

base = base.rename(columns={'Pregnancies' : 'Gestacoes', 'Glucose' : 'Glicose', 'BloodPressure' : 'PressaoArterial',
                            'SkinThickness' : 'EspessuraPele', 'Insulin' : 'Insulina', 'BMI' : 'IMC',
                            'DiabetesPedigreeFunction' : 'PedigreeDiabetes', 'Age' : 'Idade', 'Outcome' : 'Resultado'})

base.head()

,Gestacoes,Glicose,PressaoArterial,EspessuraPele,Insulina,IMC,PedigreeDiabetes,Idade,Resultado
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# Verificando novamente os tipos de dados

base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gestacoes         2460 non-null   int64
 1   Glicose           2460 non-null   int64
 2   PressaoArterial   2460 non-null   int64
 3   EspessuraPele     2460 non-null   int64
 4   Insulina          2460 non-null   int64
 5   IMC               2460 non-null   float64
 6   PedigreeDiabetes  2460 non-null   float64
 7   Idade             2460 non-null   int64
 8   Resultado         2460 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 173.1 KB

In [ ]:
# Mostrando o numero de dados faltantes em cada coluna
base.isnull().sum()

# (Num tem)

Gestacoes           0
Glicose             0
PressaoArterial     0
EspessuraPele       0
Insulina            0
IMC                 0
PedigreeDiabetes    0
Idade               0
Resultado           0
dtype: int64

In [ ]:
base[['Glicose', 'Idade']].describe()

           Glicose        Idade
count  2460.000000  2460.000000
mean    121.602033    32.821951
std      31.789270    11.251208
min       0.000000    21.000000
25%     100.000000    24.000000
50%     117.000000    29.000000
75%     142.000000    39.000000
max     197.000000    81.000000

In [ ]:
classes_diabete = dados['Resultado'].valueCounts()
classes_diabete
# print(classes_diabete)

In [ ]:
sns.countplot(x='Resultado', data=dados)
plt.show()

In [ ]:
# Gráfico de Pizza

nome_classes = ['Não tem diabetes', 'Tem diabetes']
quantidade_classes = [1500,960]
fig = plt.figure(figsize =(5, 5))
plt.pie(quantidade_classes, labels = nome_classes, autopct='%1.2f%%')
plt.show()

# Aprendizado de Máquina Supervisionado

In [ ]:
# Importanto técnicas de avaliação de modelos de classificação
from sklearn.model_selection import train_test_split  #método de  particionamento dos dados em treino e teste
from sklearn.metrics import accuracy_score    # método para calcular a taxa de acerto
import numpy as np

# Importando as técnicas de aprendizagem (Classificadores)
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [ ]:

#base_nova = dados[['nome1','nome2','nome3','variavel saida']]

# Separação aleatória em conjuntos de treino e teste  (Treino = Para etapa de aprendizagem;  Teste = Para avaliar  o desempenho do modelo em novos dados)array = aprovacao_alunos.values
X = dados[['Gestacoes',	'Glicose',	'PressaoArterial',	'EspessuraPele',	'Insulina',	'IMC', 'Idade']]   # X = variáveis explicativas
Y = dados['Resultado']  # Y = variável resposta

In [ ]:
np.random.seed(7)
X_treino, X_teste, Y_treino, Y_teste = train_test_split(X, Y, test_size=0.25) # Consideram treino 75% e teste 25%

In [ ]:
# Arvore de Decisão
modelo1 = ArvoreDecisao()
modelo1.fit(X_treino, Y_treino)  #fit é o método para treinamento dos modelos

# SVM
modelo2 = SVM(kernel = "linear")
modelo2.fit(X_treino, Y_treino)

In [ ]:
predicao1 = modelo1.predicao(X_teste)

print(predicao1)

In [ ]:
print(Y_teste)

In [ ]:
# Estimativas na base de teste (dados não vistos/futuros) = simulando o desempenho do modelo no mundo real
predicao1 = modelo1.predicao(X_teste)  # predict retorna a resposta dada pelo modelo
print("Taxa de Acerto com Arvore de Decisão = ", round((accuracy_score(Y_teste, predicao1)*100),2), "%")

predicao2 = modelo2.predicao(X_teste)
print("Taxa de Acerto com SVM = ", round((accuracy_score(Y_teste, predicao2)*100),2), "%")

In [ ]:
pacientes = {
    'Gestacoes': [2, 7],
    'Glicose': [90, 133],
    'PressaoArterial': [68, 84],
    'EspessuraPele': [42,0],
    'Insulina': [0, 0],
    'IMC': [38.2, 40.2],
    'Idade': [27, 37]
}

df_pacientes = pd.DataFrame(pacientes)

print(df_pacientes)

In [ ]:
predicoes = modelo1.predicao(df_pacientes)

for paciente in previsoes:
  if paciente == 1.0:
    print('O paciente ', int(paciente) + 1, ' possui alto risco de estar ou desenvolver diabetes')
  else:
    print( 'O paciente', int(paciente) + 1, ' não possui alto risco de desenvolver diabetes')